### ISSUE TITLE
Typo: date <> data

### ISSUE THREAD

**Issue by atomutek** [mercari/ml-system-design-pattern#18]
### What is your issue?

A few typos are present where `data` is written as `date`.

### Why is it issue?

Because `date` and `data` have different meaning.

### Where are the issues?
I ran `grep -rnw . -e '[D|d]ate'` and from what I can see, the typos are there.

> ./README_ja.md:106:- [Date model versioning pattern](./Operation-patterns/Data-model-versioning-pattern/design_ja.md)
> ./README.md:103:- [Date model versioning pattern](./Operation-patterns/Data-model-versioning-pattern/design_en.md)
> ./Lifecycle-patterns/Train-then-serve-pattern/Operation-patterns/Data-model-versioning-pattern/design_en.md:36:- Date retrieval (`model-name x.y.z-DATA.split`)
> ./Lifecycle-patterns/Train-then-serve-pattern/Operation-patterns/Data-model-versioning-pattern/design_en.md:53:#### Date retrieval (`model-name x.y.z-DATA.split`) and Release version (`model-name X.y.z-data.split`)
> ./Operation-patterns/Data-model-versioning-pattern/design_en.md:36:- Date retrieval (`model-name x.y.z-DATA.split`)
> ./Operation-patterns/Data-model-versioning-pattern/design_en.md:53:#### Date retrieval (`model-name x.y.z-DATA.split`) and Release version (`model-name X.y.z-data.split`)

**Comment by shibuiwilliam** [comment]
fixed.
https://github.com/mercari/ml-system-design-pattern/pull/20
