### ISSUE TITLE
Translate into Korean

### ISSUE THREAD

**Issue by jiyeonseo** [mercari/ml-system-design-pattern#30]
### What is your issue?
Thank you for this amazing job. I'm an engineer from Korea and working as a software engineer to create real world services using ML.  
I'd like to translate this into Korean for sharing this awesome works to more engineers 🤓 

### How do you expect to be?

**Comment by shibuiwilliam** [comment]
Thanks @jiyeonseo !
I am glad that the work is translated to Korean.
I am not familiar with the language at all, but I am happy to explain the meaning of sentences if you are not sure with my Japanese or English.

**Comment by jiyeonseo** [comment]
Nice! Thanks! I'm not a professional translator as well but will do my best ;)

**Comment by zzsza** [comment]
오 저도 앞부분 조금 번역했는데, 치즈님 번역 기다려야겠네요!!! 감사합니당 :)

**Comment by jiyeonseo** [comment]
@zzsza !!! 저도 아직 앞부분 입니다 ㅎㅎ 혹시 해주신게 있으면 먼저 PR 보내주시면 제가 이어서 해도 좋고 나눠서 해도 좋습니다 🤓 (그리고 실례가 되지 않는다면 코드리뷰 요청드려도 될까요? 😇)

**Comment by zzsza** [comment]
@jiyeonseo 
그럼 나눠서 같이 해볼까요~~? 코드리뷰 당연히 좋아요!! :)

그럼 연락할 수단이 필요할 것 같은데 페이스북 메신져 등으로 드려도 될까요~!

**Comment by jiyeonseo** [comment]
@zzsza 물론이죠!!!!! :) 혼자 하면 좀 버거웠을텐데 벌써 왕 신나네요!! 

@shibuiwilliam Sorry for just talking in Korean. I think you've already translated our conversation above lol. Anyway, just noticed we both want to work on this and decided to collaborate! Yay! not much plan yet but good news is that this will be done faster with much better quality!

**Comment by shibuiwilliam** [comment]
@jiyeonseo @zzsza 
감사합니다 !!!
I am very glad to hear that you two collaborate to improve the design patterns.
While I am not able to read/write Korean, I am always welcome to support your works. Thank you!

**Comment by shibuiwilliam** [comment]
@jiyeonseo @zzsza 감사!
I have just merged the PR. Thank you very much!

**Comment by shibuiwilliam** [comment]
@jiyeonseo @zzsza 

I have written a book about the machine learning system design patterns in Japanese this year, and surprising that it is translated to Korean!
I would like to send them to you two to tell my big appreciation.
Could you DM me your addresses? Facebook messenger is good. https://www.facebook.com/yusuke.shibui

![image](https://user-images.githubusercontent.com/23517545/145524314-7313154c-3e1f-44a1-9a5c-b187f02397fc.png)
