### ISSUE TITLE
A indentation error on "Microservice vertical pattern" page

### ISSUE THREAD

**Issue by Jasonnor** [mercari/ml-system-design-pattern#35]
### What is your issue?

Hello there, I found an indentation error on [this page](https://mercari.github.io/ml-system-design-pattern/Serving-patterns/Microservice-vertical-pattern/design_en.html
), located in the [Needs consideration] section.

![image](https://user-images.githubusercontent.com/7609173/91470258-1368e980-e8c7-11ea-842b-01cf089bb2a3.png)

Although there is no error in the Markdown file of this repo. 

### Why is it issue?

Maybe just a mistake

### How do you expect to be?

![image](https://user-images.githubusercontent.com/7609173/91470462-51660d80-e8c7-11ea-8fac-1d29ec6cb127.png)

Great design pattern summary anyway! 😄

**Comment by shibuiwilliam** [comment]
@Jasonnor 
Thank you for the issue.
Just fixed the indentation.
https://github.com/mercari/ml-system-design-pattern/pull/39
